:05/20/25 /usr/bin/riscv64-unknown-elf-gcc was installed with apt on 05/19/25 git clone https://github.com/develone/riscv-gnu-toolchain.git -b test-dev Cloning into 'riscv-gnu-toolchain'... remote: Enumerating objects: 9391, done. remote: Counting objects: 100% (462/462), done. remote: Compressing objects: 100% (124/124), done. remote: Total 9391 (delta 395), reused 338 (delta 338), pack-reused 8929 (from 3) Receiving objects: 100% (9391/9391), 6.44 MiB | 17.49 MiB/s, done. Resolving deltas: 100% (4682/4682), done. devel@pi5-90:~ $ cd riscv-gnu-toolchain/
devel@pi5-90:~/riscv-gnu-toolchain $ ./configure --prefix=/home/devel/.local/riscv --with-arch=rv32gc --with-abi=ilp32d
devel@pi5-90:~/riscv-gnu-toolchain $ make linux

devel@pi5-90:~ $ ls .local/riscv/bin
riscv32-unknown-linux-gnu-addr2line  riscv32-unknown-linux-gnu-gcc-14.2.0     riscv32-unknown-linux-gnu-gfortran  riscv32-unknown-linux-gnu-ranlib
riscv32-unknown-linux-gnu-ar         riscv32-unknown-linux-gnu-gcc-ar         riscv32-unknown-linux-gnu-gprof     riscv32-unknown-linux-gnu-readelf
riscv32-unknown-linux-gnu-as         riscv32-unknown-linux-gnu-gcc-nm         riscv32-unknown-linux-gnu-gstack    riscv32-unknown-linux-gnu-run
riscv32-unknown-linux-gnu-c++        riscv32-unknown-linux-gnu-gcc-ranlib     riscv32-unknown-linux-gnu-ld        riscv32-unknown-linux-gnu-size
riscv32-unknown-linux-gnu-c++filt    riscv32-unknown-linux-gnu-gcov           riscv32-unknown-linux-gnu-ld.bfd    riscv32-unknown-linux-gnu-strings
riscv32-unknown-linux-gnu-cpp        riscv32-unknown-linux-gnu-gcov-dump      riscv32-unknown-linux-gnu-lto-dump  riscv32-unknown-linux-gnu-strip
riscv32-unknown-linux-gnu-elfedit    riscv32-unknown-linux-gnu-gcov-tool      riscv32-unknown-linux-gnu-nm
riscv32-unknown-linux-gnu-g++        riscv32-unknown-linux-gnu-gdb            riscv32-unknown-linux-gnu-objcopy
riscv32-unknown-linux-gnu-gcc        riscv32-unknown-linux-gnu-gdb-add-index  riscv32-unknown-linux-gnu-objdump
devel@pi5-90:~ $ ls .local/riscv
bin  include  lib  libexec  riscv32-unknown-linux-gnu  share  sysroot

devel@pi5-90:~/PipelineC/examples/pico-ice/ice_makefile_pipelinec/risc-v $ ls /home/devel/.local/riscv/sysroot/usr/include/gnu
libc-version.h  lib-names.h  lib-names-ilp32d.h  stubs.h  stubs-ilp32d.h

devel@pi5-90:~/PipelineC/examples/pico-ice/ice_makefile_pipelinec/risc-v $ less /home/devel/.local/riscv/sysroot/usr/include/gnu/stubs-ilp32d.h
/* This file is automatically generated.
   It defines a symbol `__stub_FUNCTION' for each function
   in the C library which is a stub, meaning it will fail
   every time called, usually setting errno to ENOSYS.  */

 #error Applications may not define the macro _LIBC

devel@pi5-90:~/PipelineC/examples/pico-ice/ice_makefile_pipelinec/risc-v $ make hex
riscv32-unknown-linux-gnu-gcc -O3 bootstrap.S main.c -lm -o main -march=rv32i -mabi=ilp32 -mstrict-align -nostartfiles -T link.ld
In file included from /home/devel/.local/riscv/sysroot/usr/include/features.h:548,
                 from /home/devel/.local/riscv/sysroot/usr/include/bits/libc-header-start.h:33,
                 from /home/devel/.local/riscv/sysroot/usr/include/stdint.h:26,
                 from /home/devel/.local/riscv/lib/gcc/riscv32-unknown-linux-gnu/14.2.0/include/stdint.h:9,
                 from main.c:1:
/home/devel/.local/riscv/sysroot/usr/include/gnu/stubs.h:8:11: fatal error: gnu/stubs-ilp32.h: No such file or directory
    8 | # include <gnu/stubs-ilp32.h>
      |           ^~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:9: all] Error 1

devel@pi5-90:~/PipelineC/examples/pico-ice/ice_makefile_pipelinec/
make clean all PIPELINEC_TOP=risc-v/risc-v_top.c PLL_CLK_MHZ=16.0